# Generated by Django 4.0.4 on 2022-04-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.FileField(max_length=500, upload_to='course/'),
        ),
    ]
